-- ORG-038 | REVIEW DRAFT, NOT A FLYWAY MIGRATION.
-- Baseline: HidraAPI main 0c765c9e6614845eb3084bd19781554c79ba3a05 (2026-09-24).
-- Do NOT apply to an existing database before ORG-037 evidence and ADR-0006
-- are approved and an available Flyway version is rechecked.
-- Test only on an approved disposable PostgreSQL clone with transaction rollback.
-- This file deliberately DOES NOT backfill, alter UUID/string organization IDs,
-- remove legacy columns, make responsibility.scope_id NOT NULL, or authorize
-- unresolved owner references.

BEGIN;

CREATE TABLE hidra_org_operational_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operational_scope_type VARCHAR(80) NOT NULL,
    target_id VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_hidra_org_scope_type_and_target CHECK (
        (operational_scope_type = 'GLOBAL' AND target_id IS NULL)
        OR
        (operational_scope_type IN ('ORGANIZATION_UNIT', 'PIPELINE_SYSTEM',
                                    'PIPELINE', 'FACILITY', 'EQUIPMENT')
         AND target_id IS NOT NULL AND BTRIM(target_id) <> '')
    )
);

-- The same target ID may exist for DIFFERENT scope types; per-type identity is unique.
CREATE UNIQUE INDEX ux_hidra_org_scope_typed_target
    ON hidra_org_operational_scope (operational_scope_type, target_id)
    WHERE operational_scope_type <> 'GLOBAL';

-- GLOBAL identifies a unique registry row without an underlying target ID.
CREATE UNIQUE INDEX ux_hidra_org_scope_global
    ON hidra_org_operational_scope (operational_scope_type)
    WHERE operational_scope_type = 'GLOBAL';

-- Keep the legacy tuple until independently verified backfill and consumer cutover.
-- NULL permits the existing responsibility rows to survive an additive rollout.
ALTER TABLE hidra_org_responsibility_assignment
    ADD COLUMN scope_id BIGINT;

ALTER TABLE hidra_org_responsibility_assignment
    ADD CONSTRAINT fk_hidra_org_responsibility_scope
    FOREIGN KEY (scope_id) REFERENCES hidra_org_operational_scope(id)
    ON DELETE RESTRICT;

CREATE INDEX ix_hidra_org_responsibility_scope_id
    ON hidra_org_responsibility_assignment(scope_id);

-- Draft intentionally leaves the transaction uncommitted and rolls back all changes.
-- After approval, move reviewed statements into a NEW uniquely numbered Flyway
-- migration, REMOVE BEGIN/ROLLBACK and execute only through Flyway.
ROLLBACK;
