# PostgreSQL settings required for pgBackRest WAL archiving.
archive_mode=on
archive_command='pgbackrest --stanza=hidra archive-push %p'
archive_timeout=60s
restore_command='pgbackrest --stanza=hidra archive-get %f "%p"'
