/**
 *
 * @Project     : HidraAPI
 * @Product     : Hidra - Hydrocarbon Intelligence for Data, Risk, and Analytics
 * @Author      : Abir MEDJERAB
 * @Owner       : Sonatrach / TRC : Digitalization Initiative
 *
 * @Name        : TopologyPhysicalNetworkRevisionCodecTest
 * @CreatedOn   : 2025-06-26
 * @UpdatedOn   : 2026-10-09
 *
 * @Type        : Class
 * @Layer       : Infrastructure Test
 * @Module      : topology
 * @Package     : dz.sh.hidra.modules.topology.infrastructure.persistence.adapter
 *
 * @Description : Verifies independent canonical bytes, exact scalar preservation and strict decoding.
 *
 */
package dz.sh.hidra.modules.topology.infrastructure.persistence.adapter;

import dz.sh.hidra.modules.topology.domain.exception.InvalidTopologyValueException;
import dz.sh.hidra.modules.topology.domain.model.TopologyPhysicalNetworkRevision;
import dz.sh.hidra.modules.topology.domain.model.TopologyPhysicalNetworkRevision.*;
import java.math.BigDecimal;
import java.nio.ByteBuffer;
import java.time.Instant;
import java.util.Arrays;
import java.util.HexFormat;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TopologyPhysicalNetworkRevisionCodecTest {
    // Independently packed signed big-endian lengths/scales/seconds with Python struct,
    // explicit literal fields and hashlib SHA-256; never generated by the codec under test.
    private static final String HEX = "0000002248494452415f544f504f4c4f47595f504859534943414c5f4e4554574f524b5f5631"
            + "0000000173000000017200000008504950454c494e450000000171ffffffffffffffff075bcd15fffffffffffffffe3ade68b1"
            + "000000000953594e5448455449430000000178000000020000000161000000052d312e30300000000200000001620000000130"
            + "000000000000000100000001700000000162000000016100000003313030fffffffe00000004302e3530000000020000000130"
            + "00000000000000010000000165000000016100000001620000000556414c5645";
    private static final String DIGEST = "58a7fbb9800a4c67b3f1cf448e268ab44b9e49f71ed120213c6e5deeb3eb4613";
    private final TopologyPhysicalNetworkRevisionCodec codec = new TopologyPhysicalNetworkRevisionCodec();

    @Test
    void matchesIndependentExpectedBytesAndDigestIncludingNegativeDecimalScale() {
        byte[] expected = HexFormat.of().parseHex(HEX);
        assertArrayEquals(expected, codec.encode(fixture()));
        assertEquals(DIGEST, codec.sha256(expected));
        assertEquals(fixture(), codec.decode(expected));
        assertEquals(-2, codec.decode(expected).pipeSegments().get(0).lengthMeters().scale());
    }

    @Test
    void preservesNegativeEpochNanosecondsOptionalEndAndDefensiveBytes() {
        var open = fixture();
        byte[] original = codec.encode(open);
        var value = codec.decode(original);
        original[0] = 99;
        assertEquals(open, value);
        assertEquals(Instant.ofEpochSecond(-1, 123456789), value.recordedAt());
        assertEquals(Instant.ofEpochSecond(-2, 987654321), value.effectiveFrom());
        assertNull(value.effectiveUntil());
        var closed = copy(open, "s", "r", ScopeType.PIPELINE_SYSTEM, "q", open.recordedAt(), open.effectiveFrom(),
                open.effectiveFrom().plusNanos(1), Origin.DECLARED_PARAMETER, "x", open.nodes(), open.pipeSegments(), open.equipmentLinks());
        assertEquals(closed, codec.decode(codec.encode(closed)));
        assertNotEquals(DIGEST, codec.sha256(codec.encode(closed)));
        byte[] again = codec.encode(open);
        assertArrayEquals(HexFormat.of().parseHex(HEX), again);
    }

    @Test
    void digestIncludesEveryMetadataFieldAndOrderedIncidence() {
        var f = fixture();
        for (var changed : List.of(
                copy(f,"s2","r",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x",f.nodes(),f.pipeSegments(),f.equipmentLinks()),
                copy(f,"s","r2",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x",f.nodes(),f.pipeSegments(),f.equipmentLinks()),
                copy(f,"s","r",ScopeType.PIPELINE_SYSTEM,"q",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x",f.nodes(),f.pipeSegments(),f.equipmentLinks()),
                copy(f,"s","r",f.scopeType(),"q2",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x",f.nodes(),f.pipeSegments(),f.equipmentLinks()),
                copy(f,"s","r",f.scopeType(),"q",f.recordedAt().plusNanos(1),f.effectiveFrom(),null,f.origin(),"x",f.nodes(),f.pipeSegments(),f.equipmentLinks()),
                copy(f,"s","r",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom().plusNanos(1),null,f.origin(),"x",f.nodes(),f.pipeSegments(),f.equipmentLinks()),
                copy(f,"s","r",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom(),null,Origin.DECLARED_PARAMETER,"x",f.nodes(),f.pipeSegments(),f.equipmentLinks()),
                copy(f,"s","r",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x2",f.nodes(),f.pipeSegments(),f.equipmentLinks()),
                copy(f,"s","r",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x",List.of(f.nodes().get(1),f.nodes().get(0)),f.pipeSegments(),f.equipmentLinks()),
                copy(f,"s","r",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x",List.of(new Node("a",new BigDecimal("-1.000")),f.nodes().get(1)),f.pipeSegments(),f.equipmentLinks()),
                copy(f,"s","r",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x",f.nodes(),List.of(new PipeSegment("p","a","b",new BigDecimal("1E+2"),new BigDecimal("0.50"),BigDecimal.ZERO)),f.equipmentLinks()),
                copy(f,"s","r",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x",f.nodes(),f.pipeSegments(),List.of(new EquipmentLink("e","b","a",EquipmentKind.COMPRESSOR))))) {
            assertNotEquals(DIGEST, codec.sha256(codec.encode(changed)));
            assertEquals(changed, codec.decode(codec.encode(changed)));
        }
        for (int field = 0; field < 3; field++) {
            var p = f.pipeSegments().get(0);
            var changed = new PipeSegment("p","b","a",field==0?new BigDecimal("101"):p.lengthMeters(),
                    field==1?new BigDecimal("0.51"):p.internalDiameterMeters(),
                    field==2?new BigDecimal("0.001"):p.absoluteRoughnessMeters());
            var v = copy(f,"s","r",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x",f.nodes(),List.of(changed),f.equipmentLinks());
            assertNotEquals(DIGEST,codec.sha256(codec.encode(v)));
        }
    }

    @Test
    void rejectsEveryTruncationTrailingBytesUnknownFormatAndNullArguments() {
        byte[] bytes = HexFormat.of().parseHex(HEX);
        for (int end = 0; end < bytes.length; end++) {
            byte[] truncated = Arrays.copyOf(bytes,end);
            assertThrows(InvalidTopologyValueException.class, () -> codec.decode(truncated));
        }
        assertThrows(InvalidTopologyValueException.class, () -> codec.decode(Arrays.copyOf(bytes,bytes.length+1)));
        bytes[37] = '2';
        assertThrows(InvalidTopologyValueException.class, () -> codec.decode(bytes));
        assertThrows(InvalidTopologyValueException.class, () -> codec.decode(null));
        assertThrows(InvalidTopologyValueException.class, () -> codec.encode(null));
        assertThrows(InvalidTopologyValueException.class, () -> codec.sha256(null));
    }

    @Test
    void rejectsMalformedLengthsCountsUtf8MarkersEnumsNanosAndNoncanonicalDecimals() {
        for (int offset : new int[]{0,38,108}) {
            for (int value : new int[]{-1,Integer.MAX_VALUE}) {
                byte[] bytes = HexFormat.of().parseHex(HEX);
                ByteBuffer.wrap(bytes).putInt(offset,value);
                assertThrows(InvalidTopologyValueException.class, () -> codec.decode(bytes));
            }
        }
        for (int value : new int[]{-1,1_000_000_000}) {
            byte[] bytes = HexFormat.of().parseHex(HEX);
            ByteBuffer.wrap(bytes).putInt(73,value);
            assertThrows(InvalidTopologyValueException.class, () -> codec.decode(bytes));
        }
        for (int[] edit : new int[][]{{42,0xc0},{89,2},{51,'X'},{167,'1'},{168,'e'},{169,'2'},{42,' '},{118,'+'}}) {
            byte[] bytes = HexFormat.of().parseHex(HEX);
            if (edit[0]>=167 && edit[0]<=169) {
                bytes[167]='1'; bytes[168]='e'; bytes[169]='2';
            } else { bytes[edit[0]]=(byte)edit[1]; }
            assertThrows(InvalidTopologyValueException.class, () -> codec.decode(bytes));
        }
        var f=fixture();
        var malformed=copy(f,"\uD800","r",f.scopeType(),"q",f.recordedAt(),f.effectiveFrom(),null,f.origin(),"x",f.nodes(),f.pipeSegments(),f.equipmentLinks());
        assertThrows(InvalidTopologyValueException.class, () -> codec.encode(malformed));
    }

    private static TopologyPhysicalNetworkRevision fixture() {
        return new TopologyPhysicalNetworkRevision("s","r",ScopeType.PIPELINE,"q",Instant.ofEpochSecond(-1,123456789),
                Instant.ofEpochSecond(-2,987654321),null,Origin.SYNTHETIC,"x",
                List.of(new Node("a",new BigDecimal("-1.00")),new Node("b",BigDecimal.ZERO)),
                List.of(new PipeSegment("p","b","a",new BigDecimal("1E+2"),new BigDecimal("0.50"),BigDecimal.ZERO)),
                List.of(new EquipmentLink("e","a","b",EquipmentKind.VALVE)));
    }

    private static TopologyPhysicalNetworkRevision copy(TopologyPhysicalNetworkRevision ignored,String source,String revision,
            ScopeType scopeType,String scope,Instant recorded,Instant from,Instant until,Origin origin,String evidence,
            List<Node> nodes,List<PipeSegment> pipes,List<EquipmentLink> equipment) {
        return new TopologyPhysicalNetworkRevision(source,revision,scopeType,scope,recorded,from,until,origin,evidence,nodes,pipes,equipment);
    }
}
