-- HidraAPI Identity module persistence schema.
-- STB-005 — db(identity): add identity flyway migration.
-- Creates only identity-owned tables required by identity JPA entities.
-- Does not create platform, organization, topology, or future business-module tables.

CREATE TABLE IF NOT EXISTS hidra_identity_user (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    email_address VARCHAR(254) NOT NULL,
    status VARCHAR(32) NOT NULL,
    employee_reference VARCHAR(128),
    CONSTRAINT uk_hidra_identity_user_username UNIQUE (username),
    CONSTRAINT uk_hidra_identity_user_email_address UNIQUE (email_address)
);

CREATE TABLE IF NOT EXISTS hidra_identity_role (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT uk_hidra_identity_role_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS hidra_identity_permission (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(120) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT uk_hidra_identity_permission_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS hidra_identity_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    role_id VARCHAR(36) NOT NULL,
    role_code VARCHAR(64) NOT NULL,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_hidra_identity_user_role_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_hidra_identity_user_role_user
        FOREIGN KEY (user_id)
        REFERENCES hidra_identity_user (id),
    CONSTRAINT fk_hidra_identity_user_role_role
        FOREIGN KEY (role_id)
        REFERENCES hidra_identity_role (id)
);

CREATE TABLE IF NOT EXISTS hidra_identity_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id VARCHAR(36) NOT NULL,
    permission_id VARCHAR(36) NOT NULL,
    permission_code VARCHAR(120) NOT NULL,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_hidra_identity_role_permission_role_permission UNIQUE (role_id, permission_id),
    CONSTRAINT fk_hidra_identity_role_permission_role
        FOREIGN KEY (role_id)
        REFERENCES hidra_identity_role (id),
    CONSTRAINT fk_hidra_identity_role_permission_permission
        FOREIGN KEY (permission_id)
        REFERENCES hidra_identity_permission (id)
);

CREATE INDEX IF NOT EXISTS idx_hidra_identity_user_status
    ON hidra_identity_user (status);

CREATE INDEX IF NOT EXISTS idx_hidra_identity_user_employee_reference
    ON hidra_identity_user (employee_reference);

CREATE INDEX IF NOT EXISTS idx_hidra_identity_role_status
    ON hidra_identity_role (status);

CREATE INDEX IF NOT EXISTS idx_hidra_identity_user_role_user
    ON hidra_identity_user_role (user_id);

CREATE INDEX IF NOT EXISTS idx_hidra_identity_user_role_role
    ON hidra_identity_user_role (role_id);

CREATE INDEX IF NOT EXISTS idx_hidra_identity_user_role_role_code
    ON hidra_identity_user_role (role_code);

CREATE INDEX IF NOT EXISTS idx_hidra_identity_role_permission_role
    ON hidra_identity_role_permission (role_id);

CREATE INDEX IF NOT EXISTS idx_hidra_identity_role_permission_permission
    ON hidra_identity_role_permission (permission_id);

CREATE INDEX IF NOT EXISTS idx_hidra_identity_role_permission_permission_code
    ON hidra_identity_role_permission (permission_code);
