-- HIDRA organization operational-scope registry
-- Additive migration: introduces canonical registry identity without deleting legacy scope data.
-- Module: organization
--
-- IMPORTANT:
-- 1. Existing legacy responsibility rows are intentionally NOT backfilled here.
-- 2. scope_id remains nullable until verified reconciliation/backfill is completed.
-- 3. Legacy operational_scope_* columns remain in place for audit/recovery.
-- 4. Current code/name remain owned by the referenced target module and are not stored here.

CREATE TABLE hidra_org_operational_scope (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type varchar(80) NOT NULL,
    target_id varchar(120),
    CONSTRAINT ck_hidra_org_operational_scope_positive_id
        CHECK (id > 0),
    CONSTRAINT ck_hidra_org_operational_scope_shape
        CHECK (
            (scope_type = 'GLOBAL' AND target_id IS NULL)
            OR
            (
                scope_type IN (
                    'ORGANIZATION_UNIT',
                    'PIPELINE_SYSTEM',
                    'PIPELINE',
                    'FACILITY',
                    'EQUIPMENT'
                )
                AND target_id IS NOT NULL
                AND btrim(target_id) <> ''
            )
        )
);

CREATE UNIQUE INDEX uq_hidra_org_operational_scope_target
    ON hidra_org_operational_scope (scope_type, target_id)
    WHERE scope_type <> 'GLOBAL';

CREATE UNIQUE INDEX uq_hidra_org_operational_scope_global
    ON hidra_org_operational_scope (scope_type)
    WHERE scope_type = 'GLOBAL';

ALTER TABLE hidra_org_responsibility_assignment
    ADD COLUMN scope_id bigint;

ALTER TABLE hidra_org_responsibility_assignment
    ADD CONSTRAINT fk_hidra_org_responsibility_assignment_scope
    FOREIGN KEY (scope_id)
    REFERENCES hidra_org_operational_scope (id)
    ON DELETE RESTRICT;

CREATE INDEX ix_hidra_org_responsibility_assignment_scope_id
    ON hidra_org_responsibility_assignment (scope_id);

-- Permit new canonical writes without forcing fabricated values into the legacy columns.
-- The legacy columns are retained for reconciliation and later explicit retirement.
ALTER TABLE hidra_org_responsibility_assignment
    ALTER COLUMN operational_scope_type DROP NOT NULL;

ALTER TABLE hidra_org_responsibility_assignment
    ALTER COLUMN operational_scope_id DROP NOT NULL;
